spring.application.name=Finance Data Processing and Access Control Backend
# ---------- Database Configuration ----------
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# ---------- JPA / Hibernate Configuration ----------
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# ---------- Server Configuration ----------
server.port=${PORT:8080}

# ---------- JWT Secret ----------
JWT_SECRET_BASE64=${JWT_SECRET_BASE64}